package edu.njit.qvxreader;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.StringReader;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.transform.stream.StreamSource;

import org.knime.base.node.io.filereader.ColProperty;
import org.knime.core.data.DataCell;
import org.knime.core.data.DataColumnSpec;
import org.knime.core.data.DataRow;
import org.knime.core.data.DataTableSpec;
import org.knime.core.data.DataType;
import org.knime.core.data.def.DefaultRow;
import org.knime.core.data.def.DoubleCell;
import org.knime.core.data.def.IntCell;
import org.knime.core.data.def.StringCell;
import org.knime.core.node.BufferedDataContainer;
import org.knime.core.node.BufferedDataTable;
import org.knime.core.node.ExecutionContext;

import edu.njit.qvx.QvxTableHeader;
import edu.njit.qvx.QvxTableHeader.Fields.QvxFieldHeader;

public class QvxReader {
	
	/* This a prototype version of QVXReader. It can take a qvx file as input (however,
	 * will ONLY work if qvx file was generated by QVXWriter script (this is because we have no sample
	 * real qvx files to test with).
	 *  and outputs a 2D object array (Object[][])
	 * This qvx file can either be in big-endian or little-endian (needs to be tested) format.
	 * 
	 * Added functionality since last meeting:
	 * Works with various field types
	 * Various edge cases still need to be tested(such as usesSeparatorByte)
	 */
	
	private QvxTableHeader qvxTableHeader;
	private String inFileName;
	private ExecutionContext exec;
	private String[] fieldNames;
	private String xmlString;
	private byte[] buffer;
	private int bufferSize;
	private int bufferIndex = 0;
	private int zeroByteIndex;
	private List<Object[]> data = new ArrayList<>();
		
	QvxReader(){
		
	}
	
	BufferedDataTable[] readQvx(QvxReaderNodeSettings settings, ExecutionContext exec) {
		
		this.inFileName = settings.getFileName();
		this.exec = exec;
		
		System.out.println("reading from qvx table header");
		readQvxTableHeader();
		System.out.println("printing body");
		printBody();
		return null;
		//readBody();
		
		/*
		System.out.println(Arrays.toString(fieldNames));
		for(int i = 0; i < data.size(); i++) {
			System.out.println(Arrays.toString(data.get(i)));
		}*/
		
		//return new BufferedDataTable[] {dataToDataTable()};
	}
	
	private void printBody() {
		System.out.flush();
		System.out.println("Printing body...");
		bufferIndex = zeroByteIndex + 1; //Starting index of the body
		int endIndex = bufferIndex + 100;
		//buffer.length
		while(bufferIndex < endIndex) { //Keep reading until the end of the body is reached
			int value = buffer[bufferIndex++];
			if (value < 0) {
				value += 256;
			}
			System.out.println(value);
		}
	}
	
	private BufferedDataTable dataToDataTable() {
		
		/* Converts "data" (which is of type List<Object[]>) to Object[][]
		 */
		
		int numRows = data.size();
		int numCols = data.get(0).length;
		
		DataType[] dataTypes = new DataType[fieldNames.length];
		for(int i = 0; i < fieldNames.length; i++) {
			Class dataClass = data.get(0)[i].getClass();
			if (dataClass.equals(java.lang.Integer.class)){
				dataTypes[i] = IntCell.TYPE;
			}else if(dataClass.equals(java.lang.Double.class)) {
				dataTypes[i] = DoubleCell.TYPE;
			}else if(dataClass.equals(java.lang.String.class)) {
				dataTypes[i] = StringCell.TYPE;
			}else {
				throw new RuntimeException("Unknown data type");
			}
		}
		
		DataColumnSpec[] columnSpecs = DataTableSpec.createColumnSpecs(fieldNames, dataTypes);
		DataTableSpec spec = new DataTableSpec(columnSpecs);
		BufferedDataContainer buf = exec.createDataContainer(spec);
		for (int i = 0; i < numRows; i++) {
		    DataCell[] cells = new DataCell[numCols];
		    for (int j = 0; j < numCols; j++) {
		    	Object dataPt = data.get(i)[j];
		    	Class dataClass = dataPt.getClass();
		    	if (dataClass.equals(java.lang.Integer.class)) {
		    		cells[j] = new IntCell((int)dataPt);
		    	}else if(dataClass.equals(java.lang.Double.class)) {
		    		cells[j] = new DoubleCell((double)dataPt);
		    	}else if(dataClass.equals(java.lang.String.class)) {
		    		cells[j] = new StringCell((String)dataPt);
		    	}else {
					throw new RuntimeException("Unknown data type");
				}
		    }
		    DataRow row = new DefaultRow("RowKey_" + i, cells);
		    buf.addRowToTable(row);
		}
		buf.close();
		BufferedDataTable table = buf.getTable();

		return table;
	}
	
	private void readQvxTableHeader() {
		
		/* Reads the entire "inFileName", creates QvxTableHeader object, and stores the location of the
		 * zero-byte
		 */
		
		FileInputStream inputStream = null;
		try {
			// Read the entire "inFileName" into a byte[] buffer
			
			//Set bufferSize
			File f = new File(inFileName);
			bufferSize = (int)f.length();
			if (bufferSize < f.length()) { //The case when narrowing conversion causes loss of data
				throw new RuntimeException("File too big");
			}
			
			//Read "inFileName" into "buffer"
			inputStream = new FileInputStream(inFileName);
			buffer = new byte[bufferSize];
			int bytesRead = inputStream.read(buffer);
			if (bytesRead != bufferSize || inputStream.read() != -1) { // If bufferSize is not appropriate; theoretically, should never happen
				inputStream.close();
				throw new RuntimeException("Buffer size is either too big or too small");
			}
			
			// Extract the xml portion of buffer
			zeroByteIndex = indexOf(buffer, (byte)0);
			xmlString = byteArrayToString(Arrays.copyOfRange(buffer, 0, zeroByteIndex));
			
			// Unmarshal "xmlString" into a QvxTableHeader object
			JAXBContext jaxbContext;
			jaxbContext = JAXBContext.newInstance( QvxTableHeader.class );
			Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
			qvxTableHeader = (QvxTableHeader) jaxbUnmarshaller.unmarshal(
					new StreamSource(new StringReader(xmlString)));
			
			//Add field names to "data"
			List<QvxTableHeader.Fields.QvxFieldHeader> fieldHeaders =
					qvxTableHeader.getFields().getQvxFieldHeader();
			fieldNames = new String[fieldHeaders.size()];
			for(int i = 0; i < fieldHeaders.size(); i++) {
				fieldNames[i] = fieldHeaders.get(i).getFieldName();
			}
			
			inputStream.close();
		}
		catch(FileNotFoundException e) { e.printStackTrace(); }
		catch(IOException e) { e.printStackTrace(); }
		catch(JAXBException e) { e.printStackTrace(); }
	}
	
	private void readBody() {
		
		/* Reads the body of the qvx file and populates "data"
		 */
		
		int numFields = qvxTableHeader.getFields().getQvxFieldHeader().size();
		bufferIndex = zeroByteIndex + 1; //Starting index of the body
		while(bufferIndex < buffer.length) { //Keep reading until the end of the body is reached
			Object[] row = new Object[numFields];
			for(int i = 0; i < numFields; i++) { //Read each field
				QvxFieldHeader fieldHeader = qvxTableHeader.getFields().getQvxFieldHeader().get(i);			
				row[i] = readValueFromBuffer(fieldHeader);
			}
			data.add(row);
		}
			
	}
	
	private Object readValueFromBuffer(QvxFieldHeader fieldHeader) {
		
		int byteWidth = fieldHeader.getByteWidth().intValue();
		ByteOrder byteOrder = fieldHeader.isBigEndian() ? ByteOrder.BIG_ENDIAN : ByteOrder.LITTLE_ENDIAN;
		switch (fieldHeader.getType()) {
			case QVX_BLOB:
				//TODO
				return null;
			case QVX_IEEE_REAL:
				if (byteWidth == 4) {
					return ByteBuffer.wrap(readBytesFromBuffer(4)).order(byteOrder).getFloat();
				}else if(byteWidth == 8) {
					return ByteBuffer.wrap(readBytesFromBuffer(8)).order(byteOrder).getDouble();
				}
			case QVX_PACKED_BCD:
				//TODO
				return null;
			case QVX_UNSIGNED_INTEGER:
			case QVX_SIGNED_INTEGER:
				if (byteWidth == 1) {
					// TODO
				}else if(byteWidth == 2) {
					return ByteBuffer.wrap(readBytesFromBuffer(2)).order(byteOrder).getShort();
				}else if(byteWidth == 4) {
					return ByteBuffer.wrap(readBytesFromBuffer(4)).order(byteOrder).getInt();
				}else if(byteWidth == 8) {
					return ByteBuffer.wrap(readBytesFromBuffer(8)).order(byteOrder).getLong();
				}
			case QVX_TEXT:
				return bufferToString_zeroTerminated();
			default:
				return null;
		}
	}
	//Helper methods ------------------------------------
	
	private String byteArrayToString(byte[] bytes) {
		
		/* Converts each byte in bytes into a character, then concatenates all of these characters
		 */
		
		String s = "";
		for(int i = 0; i < bytes.length; i++) {
			s += (char)bytes[i];
		}
		return s;
	}
	
	private int indexOf(byte[] bytes, byte search) {
		
		/* Returns the index of the first occurrence of "search" in bytes
		 * */
		
		for(int i = 0; i < bytes.length; i++) {
			if (bytes[i] == search) {
				return i;
			}
		}
		return -1;
	}
	
	private byte[] readBytesFromBuffer(int n) {
		
		byte[] bytes = Arrays.copyOfRange(buffer, bufferIndex, bufferIndex + n);
		bufferIndex += n;
		return bytes;
	}
	
	private String bufferToString_zeroTerminated() {
		
		String s = "";
		byte b;
		while ((b = buffer[bufferIndex++]) != 0 ) {
			s += (char)b;
		}
		return s;
	}
}